In [7]:
import pandas as pd
import numpy as np

In [109]:
data=pd.read_excel("sales product-date.xlsx")

In [87]:
data.head()

,Row Labels,01-Oct,02-Oct,03-Oct,04-Oct,05-Oct,06-Oct,07-Oct,08-Oct,09-Oct,...,21-Nov,22-Nov,23-Nov,24-Nov,25-Nov,26-Nov,27-Nov,28-Nov,29-Nov,30-Nov
0,2 IN 1 CHOPPER,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3 IN1 AGARBATHI,0,1,1,1,0,0,1,0,0,...,0,0,0,2,1,0,0,0,0,0
2,3 ROSE 500GM,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3 ROSE 500GM,0,0,4,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4,"3 ROSES 250G,",0,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [88]:
data

,Row Labels,01-Oct,02-Oct,03-Oct,04-Oct,05-Oct,06-Oct,07-Oct,08-Oct,09-Oct,...,21-Nov,22-Nov,23-Nov,24-Nov,25-Nov,26-Nov,27-Nov,28-Nov,29-Nov,30-Nov
0,2 IN 1 CHOPPER,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3 IN1 AGARBATHI,0,1,1,1,0,0,1,0,0,...,0,0,0,2,1,0,0,0,0,0
2,3 ROSE 500GM,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3 ROSE 500GM,0,0,4,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4,"3 ROSES 250G,",0,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2503,ZED BLACK LUXURY,0,3,1,0,0,0,0,1,1,...,1,1,0,0,1,0,2,1,0,0
2504,ZED BLACK MANTHAN GOLD,0,0,0,0,0,0,0,0,0,...,0,0,0,3,0,1,1,0,0,0
2505,ZED BLACK STICKS,0,0,1,3,2,2,0,1,0,...,1,0,3,0,0,0,1,0,3,0
2506,ZED BLACK STICKS RS10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2507,ZRD BLACK 3IN1,0,0,3,1,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,1

In [110]:
col_names=list(data.columns)[1:]

In [111]:
daily=[]
weekly=[]
std_based=[]

In [113]:
for i in data.index:
    temp=[]
    for j in col_names:
        temp.append(data[j][i])
    temp.sort()
    temp=list(set(temp))
    q1, q3= np.percentile(temp,[25,75])
    iqr = q3 - q1
    lb = q1 -(1.5 * iqr) 
    ub = q3 +(1.5 * iqr)
    for j in col_names:
        if int(data[j][i])>ub:
            if j=="20-Oct" or j=="21-Oct" or j=="22-Oct" or j=="23-Oct" or j=="24-Oct" or j=="25-Oct" or j=="26-Oct" or j=="27-Oct" or j=="28-Oct":
                print(data['Row Labels'][i])
                daily.append(data['Row Labels'][i])
         
    for j in col_names:
        if int(data[j][i])<lb:
            if j=="20-Oct" or j=="21-Oct" or j=="22-Oct" or j=="23-Oct" or j=="24-Oct" or j=="25-Oct" or j=="26-Oct" or j=="27-Oct" or j=="28-Oct":
                print(data['Row Labels'][i])

BL GRAM FLOUR 500G
BRU RS2
COMFORT RS3.
DHEEPAM OIL
ELLU WHITE 250GM
EXO SAFAI
FROOTI RS10
HORLICKS RS5
IDHAYAM OIL
JAMS
KARPOORAM
KIT KAT 5
LOTTE CHOCO PIE
NATTU VELLAM 1 KG
ORANGE SP
RAGI 2 GK
SOAN PAPADI
SUNRISE RS10`
SURFEXCL RS20
VELLAM SPL 1KG
VELLAM SPL 1KG
VELLAM SPL 1KG
VIM SOAP RS10
YIPPEE NOODLES 420G

In [95]:
data2=pd.read_excel("sales product-week.xlsx")

In [96]:
data2

,Row Labels,Week 1,Week 2,Week 3,Week 4,Week 5,Week 6,Week 7,Week 8,Week 9
0,2 IN 1 CHOPPER,0,0,1,0,0,0,0,0,0
1,3 IN1 AGARBATHI,4,0,1,0,1,0,1,3,0
2,3 ROSE 500GM,1,0,0,0,0,0,0,0,0
3,3 ROSE 500GM,5,1,6,3,4,3,5,1,2
4,"3 ROSES 250G,",2,2,5,2,2,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...
2503,ZED BLACK LUXURY,4,6,0,3,5,0,2,5,3
2504,ZED BLACK MANTHAN GOLD,0,0,0,0,0,0,0,3,2
2505,ZED BLACK STICKS,8,9,4,5,6,4,3,5,4
2506,ZED BLACK STICKS RS10,0,0,0,5,0,0,0,0,0
2507,ZRD BLACK 3IN1,4,0,4,1,5,4,5,2,1

In [97]:
col_names2=list(data2.columns)[1:]

In [98]:
for i in data2.index:
    temp=[]
    for j in col_names2:
        temp.append(data2[j][i])
    temp.sort()
    temp=list(set(temp))
    q1, q3= np.percentile(temp,[25,75])
    iqr = q3 - q1
    lb = q1 -(1.5 * iqr) 
    ub = q3 +(1.5 * iqr)
    for j in col_names2:
        if int(data2[j][i])>ub:
            if j=="Week 4":
                print(data2['Row Labels'][i])
                weekly.append(data2['Row Labels'][i])
        if int(data2[j][i])<lb:
            if j=="Week 4":
                print(data2['Row Labels'][i])

3 ROSES RS 10
BATHI STAND
ELLU WHITE 250GM
FROOTI 150 ML
GOODDAY CASHEW COOKIES
HIDE & SEEK 120G
ICE CREAM
JAMS
KOKO KRUNCH
MM STANDARD
ORANGE SP
SAKTHI MALLI POWDER 200G
SAKTHI RASAM POWDER 50 GM
SANTOOR SANDAL TURMERIC 90G
SOAN PAPADI
SODA 100 GM
VELLAM SPL 1KG

In [99]:
data3=pd.read_excel("sales product-week for std.xlsx")

In [100]:
data3

,Row Labels,std 1,std 2,std 3,std 4,std 5,std 6,std 7,std 8,std 9
0,2 IN 1 CHOPPER,0.000000,0.000000,0.349927,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,3 IN1 AGARBATHI,0.494872,0.000000,0.349927,0.000000,0.349927,0.000000,0.349927,0.728431,0.000000
2,3 ROSE 500GM,0.349927,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3 ROSE 500GM,1.385051,0.349927,0.832993,0.494872,0.494872,0.728431,1.030158,0.349927,0.489898
4,"3 ROSES 250G,",0.451754,0.451754,0.699854,0.451754,0.451754,0.349927,0.451754,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
2503,ZED BLACK LUXURY,1.049781,0.638877,0.000000,0.494872,0.699854,0.000000,0.451754,0.699854,0.800000
2504,ZED BLACK MANTHAN GOLD,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.049781,0.489898
2505,ZED BLACK STICKS,1.124858,1.030158,0.728431,1.030158,0.989743,0.494872,0.494872,1.030158,1.166190
2506,ZED BLACK STICKS RS10,0.000000,0.000000,0.000000,1.749636,0.000000,0.000000,0.000000,0.000000,0.000000
2507,ZRD BLACK 3IN1,1.049781,0.000000,0.903508,0.349927,0.880631,0.728431,0.880631,0.699854,0.400000

In [101]:
col_names3=list(data3.columns)[1:]

In [102]:
for i in data3.index:
    temp=[]
    for j in col_names3:
        temp.append(data3[j][i])
    temp.sort()
    temp=list(set(temp))
    q1, q3= np.percentile(temp,[25,75])
    iqr = q3 - q1
    lb = q1 -(1.5 * iqr) 
    ub = q3 +(1.5 * iqr)
    for j in col_names3:
        if int(data3[j][i])>ub:
            if j=="std 4":
                print("MORE:",data3['Row Labels'][i],j,data3[j][i])
                std_based.append(data3['Row Labels'][i])
        '''if int(data3[j][i])<lb:
            if j=="std 4":
                print("LESS:",data3['Row Labels'][i],j,data3[j][i])'''

MORE: 3 ROSES RS 10     std 4 4.865538961693257
MORE: ARASAN SUPER SOAP.     std 4 9.147320339189784
MORE: BL GRAM FLOUR 500G     std 4 7.362342129557215
MORE: CHIK SAMPOO RS.1     std 4 3.1102201510110343
MORE: COMFORT FABRIC LILY FRESH 220ML     std 4 1.2453996981544782
MORE: COMFORT RS3.     std 4 18.59888080898791
MORE: DHEEPAM OIL     std 4 3.4934340744678525
MORE: FROOTI 150 ML     std 4 2.138089935299395
MORE: GOLD WINNER 5LTR(CAN)     std 4 4.2378277069118075
MORE: GRAM DHAL 500 GM     std 4 3.0237157840738176
MORE: HORLICKS RS5     std 4 9.100347604933134
MORE: ICE CREAM     std 4 6.184245949118104
MORE: JAMS     std 4 7.464200272921789
MORE: KARPOORAM     std 4 5.627918743883488
MORE: LAYS 20     std 4 2.0603150145508513
MORE: MILK     std 4 5.1110125199995196
MORE: MYSORE SANDAL FRESHNOL BUY 1 GET 1 FREE     std 4 1.0497813183356477
MORE: ORANGE SP     std 4 10.497813183356477
MORE: PARIS SUGAR     std 4 5.1269595556932455
MORE: PONDS RS10,     std 4 2.0995626366712954
MORE: RAGI 2 GK     std 4 3.45820526768863
MORE: SEERAGAM 100 GM     std 4 3.398679215248663
MORE: SOAN PAPADI     std 4 70.68527543460029
MORE: VELLAM SPL 1KG     std 4 18.98441896043453

In [81]:
data4=pd.read_excel("sales multiple size.xlsx")

In [82]:
data4

                     Row Labels  Sum of Total  Sum of Qty
0           GOLDWINNER 1LTR           96914.0         606
1     GOLD WINNER 5LTR(CAN)           65193.0          83
2            SK BULLET 25KG           64620.0          50
3                  GTS BULK           53490.0          39
4         ULUNTHU GOLLA 1KG           30686.0         238
...                         ...           ...         ...
2503            MG SAMBRINI               6.0           1
2504           BINGO CHEESE               5.0           1
2505         BOURN VITA RS5               5.0           1
2506               HORLICKS RS5           5.0           1
2507              POLO 5.00               5.0           1

[2508 rows x 3 columns]

In [83]:
data44=data4.head(500)

In [84]:
data44

                    Row Labels  Sum of Total  Sum of Qty
0          GOLDWINNER 1LTR           96914.0         606
1    GOLD WINNER 5LTR(CAN)           65193.0          83
2           SK BULLET 25KG           64620.0          50
3                 GTS BULK           53490.0          39
4        ULUNTHU GOLLA 1KG           30686.0         238
..                         ...           ...         ...
495           PULI (N)250G            1160.0          29
496      COMFORT ANTI BACT            1158.0           5
497   POND,S BRIGHT BEAUTY            1157.0           4
498     SAFFOLA OATS 400GM            1156.0          13
499           3 ROSES 500G            1155.0           3

[500 rows x 3 columns]

In [85]:
data44.to_csv("first 500.csv")

In [103]:
daily

['BL GRAM FLOUR 500G    ',
 'BRU RS2    ',
 'COMFORT RS3.    ',
 'DHEEPAM OIL    ',
 'ELLU WHITE 250GM    ',
 'EXO SAFAI    ',
 'FROOTI RS10    ',
 'HORLICKS RS5    ',
 'IDHAYAM OIL    ',
 'JAMS    ',
 'KARPOORAM    ',
 'KIT KAT 5    ',
 'LOTTE CHOCO PIE    ',
 'NATTU VELLAM 1 KG    ',
 'ORANGE SP    ',
 'RAGI 2 GK    ',
 'SOAN PAPADI    ',
 'SUNRISE RS10`    ',
 'SURFEXCL RS20    ',
 'VELLAM SPL 1KG    ',
 'VELLAM SPL 1KG    ',
 'VELLAM SPL 1KG    ',
 'VIM SOAP RS10    ',
 'YIPPEE NOODLES 420G    ']

In [104]:
weekly

['3 ROSES RS 10    ',
 'BATHI STAND    ',
 'ELLU WHITE 250GM    ',
 'FROOTI 150 ML    ',
 'ICE CREAM    ',
 'JAMS    ',
 'KOKO KRUNCH    ',
 'MM STANDARD    ',
 'ORANGE SP    ',
 'SAKTHI MALLI POWDER 200G    ',
 'SAKTHI RASAM POWDER 50 GM    ',
 'SANTOOR SANDAL TURMERIC 90G    ',
 'SOAN PAPADI    ',
 'SODA 100 GM    ',
 'VELLAM SPL 1KG    ']

In [105]:
std_based

['3 ROSES RS 10    ',
 'ARASAN SUPER SOAP.    ',
 'BL GRAM FLOUR 500G    ',
 'CHIK SAMPOO RS.1    ',
 'COMFORT FABRIC LILY FRESH 220ML    ',
 'COMFORT RS3.    ',
 'DHEEPAM OIL    ',
 'FROOTI 150 ML    ',
 'GOLD WINNER 5LTR(CAN)    ',
 'GRAM DHAL 500 GM    ',
 'HORLICKS RS5    ',
 'ICE CREAM    ',
 'JAMS    ',
 'KARPOORAM    ',
 'LAYS 20    ',
 'MILK    ',
 'MYSORE SANDAL FRESHNOL BUY 1 GET 1 FREE    ',
 'ORANGE SP    ',
 'PARIS SUGAR    ',
 'PONDS RS10,    ',
 'RAGI 2 GK    ',
 'SEERAGAM 100 GM    ',
 'SOAN PAPADI    ',
 'VELLAM SPL 1KG    ']

In [108]:
def find_common(list1, list2, list3):
    common = set()
    for elem in list1:
        if elem in list2 and elem in list3:
            common.add(elem)
    return common
 
common = find_common(daily, weekly, std_based)
print(common)

{'SOAN PAPADI    ', 'JAMS    ', 'ORANGE SP    ', 'VELLAM SPL 1KG    '}

In [ ]:
y=